import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template2",
                path_list=[[TestAction.create_data_volume_from_image, "volume1"],
                [TestAction.attach_volume, "vm1", "volume1"],
		[TestAction.create_data_volume_from_image, "volume2"],
		[TestAction.attach_volume, "vm1", "volume2"],
		[TestAction.create_data_volume_from_image, "volume3"],
		[TestAction.attach_volume, "vm1", "volume3"],
		[TestAction.create_data_volume_from_image, "volume4"],
		[TestAction.attach_volume, "vm1", "volume4"],
		[TestAction.create_data_volume_from_image, "volume5"],
		[TestAction.attach_volume, "vm1", "volume5"],
		[TestAction.create_data_volume_from_image, "volume6"],
		[TestAction.attach_volume, "vm1", "volume6"],
		[TestAction.create_data_volume_from_image, "volume7"],
		[TestAction.attach_volume, "vm1", "volume7"],
		[TestAction.create_data_volume_from_image, "volume8"],
		[TestAction.attach_volume, "vm1", "volume8"],
		[TestAction.stop_vm, "vm1"],
		[TestAction.change_vm_image, "vm1"],
		[TestAction.start_vm, "vm1"],
		[TestAction.create_volume_backup, "volume1", "backup1"],
		[TestAction.detach_volume, "volume1", "vm1"],
		[TestAction.reboot_vm, "vm1"],
		[TestAction.resize_data_volume, "volume1", 5*1024*1024],
		[TestAction.create_volume_snapshot, "volume1", 'snapshot1'],
		[TestAction.delete_volume_snapshot, 'snapshot1'],
		[TestAction.delete_volume, "volume1"],
		[TestAction.create_volume_snapshot, "vm1-root", 'snapshot1'],
		[TestAction.create_volume_backup, "volume2", "backup2"],
		[TestAction.stop_vm, "vm1"],
		[TestAction.use_volume_backup, "backup2"],
		[TestAction.create_volume_snapshot, "volume2", 'snapshot1'],
		[TestAction.create_volume_snapshot, "volume2", 'snapshot2'],
		[TestAction.create_volume_snapshot, "volume2", 'snapshot3'],
		[TestAction.create_volume_snapshot, "volume2", 'snapshot4'],
		[TestAction.create_volume_snapshot, "volume2", 'snapshot5'],
		[TestAction.batch_delete_volume_snapshot, ['snapshot4','snapshot2','snapshot5']],
		[TestAction.start_vm, "vm1"],
		[TestAction.reboot_vm, "vm1"]])
