import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template2", 
                path_list=[[TestAction.create_data_volume_from_image, "volume1", "=scsi"], 
                           [TestAction.attach_volume, "vm1", "volume1"], 
                           [TestAction.create_data_volume_from_image, "volume2", "=scsi"], 
                           [TestAction.create_data_volume_from_image, "volume3", "=scsi"], 
                           [TestAction.create_volume_snapshot, "vm1-root", "snapshot1"], 
                           [TestAction.create_volume_snapshot, "volume2", "snapshot2-1"], 
                           [TestAction.create_volume_snapshot, "volume2", "snapshot2-2"], 
                           [TestAction.create_volume_snapshot, "volume2", "snapshot2-3"], 
                           [TestAction.create_volume_snapshot, "volume2", "snapshot2-4"], 
                           [TestAction.create_volume_backup, "volume1", "backup1"], 
                           [TestAction.attach_volume, "vm1", "volume2"], 
                           [TestAction.stop_vm, "vm1"], 
                           [TestAction.use_volume_snapshot, "snapshot1"], 
                           [TestAction.create_data_vol_template_from_volume, "volume2", "image1"], 
                           [TestAction.delete_volume_snapshot, "snapshot1"], 
                           [TestAction.attach_volume, "vm1", "volume3"], 
                           [TestAction.reinit_vm, "vm1"], 
                           [TestAction.use_volume_backup, "backup1"], 
                           [TestAction.start_vm, "vm1"],
                           [TestAction.batch_delete_volume_snapshot, ["snapshot2-3","snapshot2-1","snapshot2-4"]],
                           [TestAction.reboot_vm, "vm1"]])
