import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template1", 
                path_list=[[TestAction.create_data_volume_from_image, "volume1", "=scsi"],
                           [TestAction.create_data_volume_from_image, "volume2", "=scsi"],
                           [TestAction.create_data_volume_from_image, "volume3", "=scsi"],
                           [TestAction.attach_volume, "vm1", "volume1"],
                           [TestAction.attach_volume, "vm1", "volume2"],
                           [TestAction.attach_volume, "vm1", "volume3"],
                           [TestAction.create_volume_snapshot, "vm1-root", "snapshot1"],
                           [TestAction.create_volume_snapshot, "volume1", "snapshot2"],
                           [TestAction.create_volume_snapshot, "volume1", "snapshot3"],
                           [TestAction.create_volume_snapshot, "volume1", "snapshot4"],
                           [TestAction.create_volume_snapshot, "volume1", "snapshot5"],
                           [TestAction.delete_volume, "volume2"],
                           [TestAction.stop_vm, "vm1"],
                           [TestAction.use_volume_snapshot, "snapshot1"],
                           [TestAction.resize_data_volume, "volume1", 5*1024*1024],
                           [TestAction.batch_delete_volume_snapshot, ["snapshot4", "snapshot5"]],
                           [TestAction.detach_volume, "volume3"],
                           [TestAction.create_image_from_volume, "vm1", "image1"],
                           [TestAction.use_volume_snapshot, "snapshot2"],
                           [TestAction.delete_volume_snapshot, "snapshot2"],
                           [TestAction.start_vm, "vm1"],
                           [TestAction.reboot_vm, "vm1"]])
