#!/bin/sh

# the following is chkconfig init header
#
# zstack-testagent:  zstack test agent daemon
#
# chkconfig: 345 97 03
# description:  This is a daemon instructed by zstack integration test framework \
#               to perform test related operations\
#               See http://zstack.org
#
# processname: zstacktestagent
# pidfile: /var/run/zstack/zstacktestagent.pid
#

check_status() {
	pidfile='/var/run/zstack/zstacktestagent.pid'
	if [ ! -f $pidfile ]; then
		echo "zstack test agent is stopped"
		exit 1
	else
		pid=`cat $pidfile`
		ps -p $pid > /dev/null
		if [ $? -eq 0 ]; then
			echo "zstack test agent is running, pid is $pid"
			exit 0
		else
			echo "zstack test agent is stopped, but pidfile at $pidfile is not cleaned. It may be caused by the agent crashed at last time, manually cleaning it would be ok"
			exit 1
		fi
	fi
}

if [ $# -eq 0 ]; then
	echo "usage: $0
[start|stop|restart|status]"
	exit 1
fi

if [ "$@" = "status" ]; then
	check_status
else
	. /var/lib/zstack/virtualenv/testagent/bin/activate && python -c "from zstacktestagent import zstacktestagentdaemon; zstacktestagentdaemon.main()" $@
fi

if [ $? -eq 0 ]; then
    echo "$@ zstack test agent .... SUCCESS"
    exit 0
else
    echo "$@ zstack test agent .... FAILED"
    exit 1
fi
