import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template5", path_list=[
        [TestAction.create_vm_by_image, "iso1", "iso", "vm1"],
        [TestAction.create_volume, "volume1", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume_backup, "volume1", "backup1"],
        [TestAction.delete_vm, "vm1"],
        [TestAction.expunge_vm, "vm1"],
        [TestAction.create_volume, "volume2", "=scsi,thin"],
        [TestAction.create_mini_vm, "vm2", 'data_volume=false', 'cpu=random', 'memory=2', 'network=random',
         'provisiong=thick'],
        [TestAction.create_volume, "volume3", "=scsi,thin"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.delete_volume_backup, "backup1"],
        [TestAction.delete_image, "image1"],
        [TestAction.recover_image, "image1"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.create_volume_backup, "vm2-root", "backup2"],
        [TestAction.reboot_vm, "vm2"],
        [TestAction.attach_volume, "vm2", "volume2"],
        [TestAction.detach_volume, "volume2"],
        [TestAction.delete_volume, "volume2"],
        [TestAction.create_mini_vm, "vm3", 'data_volume=false', 'cpu=random', 'memory=2', 'provisiong=thin'],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.expunge_volume, "volume2"],
        [TestAction.delete_vm, "vm3"],
        [TestAction.attach_volume, "vm2", "volume3"],
        [TestAction.create_volume_backup, "volume3", "backup3"],
        [TestAction.delete_image, "image2"],
        [TestAction.delete_volume_backup, "backup2"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume, "volume4", "=scsi,thin"]])