import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template5", path_list=[
        [TestAction.create_mini_vm, "vm1", 'data_volume=false', 'cpu=random', 'memory=2', 'provisiong=thin'],
        [TestAction.destroy_vm, "vm1"],
        [TestAction.recover_vm, "vm1"],
        [TestAction.create_volume, "volume1", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.start_vm, "vm1"],
        [TestAction.create_volume_backup, "volume1", "backup1"],
        [TestAction.stop_vm, "vm1"],
        [TestAction.create_image_from_volume, "vm1", "vm1-image1"],
        [TestAction.detach_volume, "volume1"],
        [TestAction.create_mini_vm, "vm2", 'data_volume=false', 'cpu=random', 'memory=2', 'network=random',
         'provisiong=thick'],
        [TestAction.create_volume, "volume2", "=scsi,thin"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.use_volume_backup, "backup1"],
        [TestAction.delete_image, "vm1-image1"],
        [TestAction.recover_image, "vm1-image1"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.attach_volume, "vm2", "volume2"],
        [TestAction.create_volume_backup, "volume2", "backup2"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.change_vm_ha, "vm2"],
        [TestAction.migrate_vm, "vm1"],
        [TestAction.migrate_vm, "vm2"],
        [TestAction.detach_volume, "volume1"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.delete_volume, "volume1"],
        [TestAction.expunge_volume, "volume1"],
        [TestAction.stop_vm, "vm1"],
        [TestAction.stop_vm, "vm2"],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.reboot_vm, "vm1"],
        [TestAction.create_volume_backup, "volume2", "backup3"],
        [TestAction.resize_volume, "vm2", 5 * 1024 * 1024],
        [TestAction.delete_image, "vm1-image1"],
        [TestAction.recover_image, "vm1-image1"],
        [TestAction.delete_volume_backup, "backup1"],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume, "volume3", "=scsi,thin"],
        [TestAction.attach_volume, "vm2", "volume3"]])