import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():
    return dict(initial_formation="template5", path_list=[
        [TestAction.create_mini_vm, "vm1", "data_volume=false", "cpu=2", "memory=2","provisiong=thick"],
        [TestAction.delete_vm, "vm1"],
        [TestAction.recover_vm, "vm1"],
        [TestAction.create_volume, "volume1", "=scsi,thick"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume_backup, "volume1", "data-backup1"],
        [TestAction.create_mini_vm, "vm2", "data_volume=false", "cpu=2", "memory=2","provisiong=thin"],
        [TestAction.create_volume, "volume2", "=scsi,thick"],
        [TestAction.attach_volume, "vm2", "volume2"],
        [TestAction.create_mini_vm, "vm3", "data_volume=false", "cpu=2", "memory=2","provisiong=thin","network=random"],
        [TestAction.create_volume, "volume3", "=scsi,thick"],
        [TestAction.delete_volume, "volume3"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume_backup, "vm3-root", "root-backup3"],
        [TestAction.delete_volume_backup, "root-backup3"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.create_volume_backup, "vm3-root", "root-backup3"],
        [TestAction.delete_vm, "vm3"],
        [TestAction.recover_vm, "vm3"],
        [TestAction.create_volume, "volume4", "=scsi,thick"],
        [TestAction.attach_volume, "vm3", "volume4"],
        [TestAction.detach_volume, "volume4"],
        [TestAction.delete_volume, "volume4"],
        [TestAction.create_mini_vm, "vm4", "data_volume=false", "cpu=2", "memory=2","provisiong=thin"],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.expunge_volume, "volume4"],
        [TestAction.create_vm_by_image, "iso1", "iso", "vm5"],
        [TestAction.create_volume, "volume4", "=scsi,thick"],
        [TestAction.attach_volume, "vm4", "volume4"],
        [TestAction.create_volume_backup, "volume4", "data-backup4"],
        [TestAction.delete_image, "image2"],
        [TestAction.recover_image, "image2"],
        [TestAction.use_volume_backup, "root-backup3"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume, "volume5", "=scsi,thick"],
       ])
