import zstackwoodpecker.test_state as ts_header
import os
TestAction = ts_header.TestAction
def path():

    return dict(initial_formation="template5", path_list=[
        [TestAction.create_mini_vm, "vm1", 'data_volume=false', 'cpu=random', 'memory=random', 'network=random', 'provisiong=thick'],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.create_vm_backup, "vm1", "backup1"],
        [TestAction.create_mini_vm, "vm2", 'data_volume=false', 'cpu=random', 'memory=random', 'network=random',
         'provisiong=thick'],
        [TestAction.create_volume, "volume1", "=scsi,thick"],
        [TestAction.resize_data_volume, "volume1", 5 * 1024 * 1024],
        [TestAction.create_volume, "volume2", "flag=scsi,thick", "size=random"],
        [TestAction.create_mini_vm, "vm3", 'data_volume=false', 'cpu=random', 'memory=random', 'network=random',
         'provisiong=thick'],
        [TestAction.delete_volume, "volume1"],
        [TestAction.recover_volume, "volume1"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume_backup, "volume1", "backup1"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.stop_vm, "vm1"],
        [TestAction.use_volume_backup, "backup1"],
        [TestAction.start_vm, "vm1"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.create_volume_backup, "volume1","backup2"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.resize_volume, "vm1", 5 * 1024 * 1024],
        [TestAction.resize_volume, "vm2", 5 * 1024 * 1024],
        [TestAction.resize_volume, "vm3", 5 * 1024 * 1024],
        [TestAction.attach_volume, "vm2", "volume2"],
        [TestAction.create_volume, "volume3", "flag=scsi,thick"],
        [TestAction.create_mini_vm, "vm4", 'data_volume=false', 'cpu=random', 'memory=random', 'network=random', 'provisiong=thick'],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.delete_volume, "volume2"],
        [TestAction.expunge_volume, "volume2"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.change_vm_ha, "vm2"],
        [TestAction.change_vm_ha, "vm3"],
        [TestAction.change_vm_ha, "vm4"],
        [TestAction.create_vm_backup, "vm1", "backup3"],
        [TestAction.create_vm_backup, "vm2", "backup4"],
        [TestAction.create_vm_backup, "vm3", "backup5"],
        [TestAction.create_vm_backup, "vm4", "backup6"],
        [TestAction.create_image_from_volume, "vm1", "vm1-iamge1"],
        [TestAction.create_image_from_volume, "vm2", "vm2-iamge1"],
        [TestAction.create_image_from_volume, "vm3", "vm3-iamge1"],
        [TestAction.create_image_from_volume, "vm4", "vm4-iamge1"],
        [TestAction.delete_image, "vm1-image1"],
        [TestAction.recover_image, "vm1-image1"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.change_vm_ha, "vm2"],
        [TestAction.change_vm_ha, "vm3"],
        [TestAction.change_vm_ha, "vm4"],
        [TestAction.stop_vm, "vm1"],
        [TestAction.stop_vm, "vm2"],
        [TestAction.stop_vm, "vm3"],
        [TestAction.stop_vm, "vm4"],
        [TestAction.use_vm_backup, "backup3"],
        [TestAction.use_vm_backup, "backup4"],
        [TestAction.use_vm_backup, "backup5"],
        [TestAction.use_vm_backup, "backup6"],
        [TestAction.start_vm, "vm1"],
        [TestAction.start_vm, "vm2"],
        [TestAction.start_vm, "vm3"],
        [TestAction.start_vm, "vm4"],
        [TestAction.change_vm_ha, "vm1"],
        [TestAction.change_vm_ha, "vm2"],
        [TestAction.change_vm_ha, "vm3"],
        [TestAction.change_vm_ha, "vm4"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume, "volume4", "=scsi,thick"],
        [TestAction.attach_volume, "vm4", "volume4"]])