import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():

    return dict(initial_formation="template5", path_list=[
        [TestAction.create_mini_vm, "vm1", 'data_volume=false', 'cpu=2', 'memory=2', 'provisiong=thin'],
        [TestAction.reboot_vm, "vm1"],
        [TestAction.create_volume, "volume1", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume_backup, "volume1", "backup1"],
        [TestAction.create_mini_vm, "vm2", 'data_volume=false', 'cpu=random', 'memory=2', 'provisiong=thin'],
        [TestAction.resize_data_volume, "volume1", 5*1024*1024],
        [TestAction.create_volume, "volume2", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume2"],
        [TestAction.create_mini_vm, "vm3", 'data_volume=false', 'cpu=random', 'memory=2', 'network=random', 'provisiong=thin'],
        [TestAction.create_volume, "volume3", "=scsi,thin"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.delete_volume_backup, "backup1"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.create_volume_backup, "volume1", "backup2"],
        [TestAction.create_mini_vm, "vm4", 'data_volume=false', 'cpu=random', 'memory=2', 'network=random',
         'provisiong=thin'],
        [TestAction.create_image_from_volume, "vm1", "vm1-image1"],
        [TestAction.create_image_from_volume, "vm2", "vm2-image1"],
        [TestAction.create_image_from_volume, "vm3", "vm3-image1"],
        [TestAction.create_image_from_volume, "vm4", "vm4-image1"],
        [TestAction.create_volume, "volume4", "=scsi,thin"],
        [TestAction.attach_volume, "vm4", "volume4"],
        [TestAction.delete_volume, "volume4"],
        [TestAction.recover_volume, "volume4"],
        [TestAction.stop_vm, "vm4"],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.delete_volume, "volume4"],
        [TestAction.expunge_volume, "volume4"],
        [TestAction.change_vm_ha, "vm4"],
        [TestAction.create_vm_backup, "vm4", "backup3"],
        [TestAction.create_image_from_volume, "vm4", "vm4-image2"],
        [TestAction.delete_image, "image2"],
        [TestAction.recover_image, "image2"],
        [TestAction.delete_volume_backup, "backup2"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"]])