import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():

    return dict(initial_formation="template5", path_list=[
        [TestAction.create_vm_by_image, "iso1", "iso", "vm1"],
        [TestAction.create_volume, "volume1", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume, "volume2", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume2"],
        [TestAction.create_volume, "volume3", "=scsi,thin"],
        [TestAction.attach_volume, "vm1", "volume3"],
        [TestAction.create_volume_backup, "volume1", "backup1"],
        [TestAction.destroy_vm, "vm1"],
        [TestAction.expunge_vm, "vm1"],
        [TestAction.create_mini_vm, "vm2", "data_volume=false", "cpu=2", "memory=2", "network=random", "provisiong=thin"],
        [TestAction.create_volume, "volume4", "=scsi,thick"],
        [TestAction.attach_volume, "vm2", "volume4"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_vm_backup, "vm2", "vm2-backup-1"],
        [TestAction.stop_vm, "vm2"],
        [TestAction.use_vm_backup, "vm2-backup-1"],
        [TestAction.start_vm, "vm2"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.stop_vm, "vm2"],
        [TestAction.create_vm_backup, "vm2", "vm2-backup-2"],
        [TestAction.start_vm, "vm2"],
        [TestAction.destroy_vm, "vm2"],
        [TestAction.create_volume, "volume5", "=scsi,thin"],
        [TestAction.create_volume, "volume6", "=scsi,thick"],
        [TestAction.create_mini_vm, "vm3", 'data_volume=false', 'cpu=2', 'memory=2', 'provisiong=thin'],
        [TestAction.attach_volume, "vm3", "volume5"],
        [TestAction.attach_volume, "vm3", "volume6"],
        [TestAction.stop_vm, "vm3"],
        [TestAction.add_image, "image2", 'root', "file:///opt/zstack-dvd/zstack-image-1.4.qcow2"],
        [TestAction.delete_volume, "volume5"],
        [TestAction.expunge_volume, "volume5"],
        [TestAction.create_mini_vm, "vm4", 'data_volume=false', 'cpu=2', 'memory=2', 'provisiong=thin'],
        [TestAction.create_vm_backup, "vm4", "vm4-backup-1"],
        [TestAction.delete_image, "image2"],
        [TestAction.use_vm_backup, "vm2-backup-1"],
        [TestAction.start_vm, "vm2"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.detach_volume, "volume6"]])
