import zstackwoodpecker.test_state as ts_header
TestAction = ts_header.TestAction
def path():

    return dict(initial_formation="template5", path_list=[
        [TestAction.create_mini_vm, "vm1", 'data_volume=true', 'cpu=2', 'memory=2', 'provisiong=thick'],
        [TestAction.create_volume, "volume1", "=scsi,thick"],
        [TestAction.attach_volume, "vm1", "volume1"],
        [TestAction.create_volume, "volume2", "=scsi,thick"],
        [TestAction.attach_volume, "vm1", "volume2"],
        [TestAction.reboot_vm, "vm1"],
        [TestAction.create_vm_backup, "vm1", "vm1-backup"],
        [TestAction.destroy_vm, "vm1"],
        [TestAction.expunge_vm, "vm1"],
        [TestAction.create_mini_vm, "vm2", 'data_volume=false', 'cpu=2', 'memory=2', 'provisiong=thick'],
        [TestAction.create_volume, "volume3", "=scsi,thick"],
        [TestAction.attach_volume, "vm2", "volume3"],
        [TestAction.detach_volume, "volume3"],
        [TestAction.create_mini_vm, "vm3", 'data_volume=false', 'cpu=2', 'memory=2', 'network=random',
         'provisiong=thick'],
        [TestAction.create_volume, "volume4", "=scsi,thin"],
        [TestAction.add_image, "image1", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_vm_backup, "vm2", "vm2-backup-1"],
        [TestAction.delete_image, "image1"],
        [TestAction.recover_image, "image1"],
        [TestAction.delete_image, "image1"],
        [TestAction.expunge_image, "image1"],
        [TestAction.create_vm_backup, "vm2", "vm2-backup-2"],
        [TestAction.destroy_vm, "vm2"],
        [TestAction.recover_vm, "vm2"],
        [TestAction.start_vm, "vm2"],
        [TestAction.migrate_vm, "vm2"],
        [TestAction.migrate_vm, "vm3"],
        [TestAction.attach_volume, "vm2", "volume4"],
        [TestAction.detach_volume, "volume4"],
        [TestAction.create_volume, "volume5", "=scsi,thin"],
        [TestAction.destroy_vm, "vm2"],
        [TestAction.expunge_vm, "vm2"],
        [TestAction.add_image, "image2", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.delete_volume, "volume3"],
        [TestAction.expunge_volume, "volume3"],
        [TestAction.create_mini_vm, "vm4", 'data_volume=false', 'cpu=2', 'memory=2', 'provisiong=thick'],
        [TestAction.attach_volume, "vm4", "volume2"],
        [TestAction.create_volume_backup, "volume2", "backup1"],
        [TestAction.delete_image, "image2"],
        [TestAction.delete_vm_backup, "vm2-backup-2"],
        [TestAction.add_image, "image3", 'root', "http://172.20.1.28/mirror/diskimages/centos_vdbench.qcow2"],
        [TestAction.create_volume, "volume6", "=scsi,thick"]])
